package com.yizhaoqi.smartpai.service;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.yizhaoqi.smartpai.agent.AgentService;
import com.yizhaoqi.smartpai.client.DeepSeekClient;
import com.yizhaoqi.smartpai.dto.IntentResult;
import com.yizhaoqi.smartpai.entity.SearchResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.stereotype.Service;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;

import java.time.Duration;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;

/**
 * 聊天处理服务
 * 负责处理WebSocket聊天消息和管理对话历史
 * 
 * @author Generated by Assistant
 */
@Service
public class ChatHandler {
    
    private static final Logger logger = LoggerFactory.getLogger(ChatHandler.class);
    private final RedisTemplate<String, String> redisTemplate;
    private final HybridSearchService searchService;
    private final DeepSeekClient deepSeekClient;
    private final ObjectMapper objectMapper;
    private final IntentRecognitionService intentRecognitionService;
    private final KnowledgeGraphService knowledgeGraphService;

    @Value("${ai.knowledge-graph.enabled:false}")
    private boolean knowledgeGraphEnabled;

    // 用于存储每个会话的完整响应
    private final Map<String, StringBuilder> responseBuilders = new ConcurrentHashMap<>();
    // 用于跟踪每个会话的响应完成状态
    private final Map<String, CompletableFuture<String>> responseFutures = new ConcurrentHashMap<>();
    // 停止标志 - 简单方案
    private final Map<String, Boolean> stopFlags = new ConcurrentHashMap<>();

    public ChatHandler(RedisTemplate<String, String> redisTemplate,
                      HybridSearchService searchService,
                      DeepSeekClient deepSeekClient,
                      IntentRecognitionService intentRecognitionService,
                      KnowledgeGraphService knowledgeGraphService) {
        this.redisTemplate = redisTemplate;
        this.searchService = searchService;
        this.deepSeekClient = deepSeekClient;
        this.intentRecognitionService = intentRecognitionService;
        this.knowledgeGraphService = knowledgeGraphService;
        this.objectMapper = new ObjectMapper();
    }

    public void processMessage(String userId, String userMessage, WebSocketSession session) {
        logger.info("开始处理消息，用户ID: {}, 会话ID: {}", userId, session.getId());
        try {
            // 1. 获取或创建会话 ID
            String conversationId = getOrCreateConversationId(userId);
            logger.info("会话ID: {}, 用户ID: {}", conversationId, userId);
            
            // 为当前会话创建响应构建器
            responseBuilders.put(session.getId(), new StringBuilder());
            // 创建一个CompletableFuture来跟踪响应完成状态
            CompletableFuture<String> responseFuture = new CompletableFuture<>();
            responseFutures.put(session.getId(), responseFuture);
            
            // 2. 获取对话历史
            List<Map<String, String>> history = getConversationHistory(conversationId);
            logger.debug("获取到 {} 条历史对话", history.size());

            // 3. 意图识别：决定走 RAG、知识图谱或两者
            IntentResult intent = intentRecognitionService.recognize(userMessage);
            logger.info("意图识别结果: type={}, needRag={}, needKg={}", intent.getIntentType(), intent.needRag(), intent.needKg());

            // 4. RAG 检索。KG 未接入时，原本判为 KG 的实体/关系问题也回落到文档检索。
            boolean shouldUseRag = intent.needRag()
                    || (!knowledgeGraphEnabled && intent.needKg());
            List<SearchResult> searchResults = shouldUseRag
                    ? searchService.searchWithPermission(userMessage, userId, 5)
                    : new ArrayList<>();
            logger.debug("RAG 搜索结果数量: {}", searchResults.size());

            // 5. 知识图谱未接入时默认关闭，避免把占位内容交给模型造成误导。
            String kgContext = knowledgeGraphEnabled && intent.needKg()
                    ? knowledgeGraphService.getSubgraphContext(userMessage, intent.getSlots())
                    : "";

            // 6. 合并 RAG 与 KG 上下文
            String context = knowledgeGraphEnabled
                    ? mergeContext(buildContext(searchResults), kgContext)
                    : buildRagOnlyContext(searchResults);

            // 7. 调用 DeepSeek API 并处理流式响应
            logger.info("调用DeepSeek API生成回复");
            deepSeekClient.streamResponse(userMessage, context, history, 
                chunk -> {
                    // 累积响应内容
                    StringBuilder responseBuilder = responseBuilders.get(session.getId());
                    if (responseBuilder != null) {
                        responseBuilder.append(chunk);
                    }
                    sendResponseChunk(session, chunk);
                },
                error -> {
                    // 处理错误并完成future
                    handleError(session, error);
                    // 发送响应完成通知（错误情况）
                    sendCompletionNotification(session);
                    responseFuture.completeExceptionally(error);
                    // 清理会话响应构建器
                    responseBuilders.remove(session.getId());
                    responseFutures.remove(session.getId());
                });
            
            // 8. 启动一个后台任务检查并标记响应完成
            new Thread(() -> {
                try {
                    // 等待最多30秒，给API足够的响应时间
                    Thread.sleep(3000); // 先等待3秒钟，让API有时间开始响应
                    
                    // 获取当前累积的响应内容
                    StringBuilder responseBuilder = responseBuilders.get(session.getId());
                    
                    // 如果响应构建器存在并且已有内容，认为响应已完成
                    if (responseBuilder != null) {
                        // 记录最后2秒的响应变化，检测是否停止增长
                        String lastResponse = responseBuilder.toString();
                        int lastLength = lastResponse.length();
                        
                        Thread.sleep(2000); // 再等待2秒
                        
                        // 再次检查是否有新内容
                        if (responseBuilder.length() == lastLength) {
                            // 没有新内容，可以认为响应已完成
                            responseFuture.complete(responseBuilder.toString());
                            logger.info("DeepSeek响应已完成，长度: {}", responseBuilder.length());
                            
                            // 发送响应完成通知
                            sendCompletionNotification(session);
                            
                            // 更新对话历史
                            String completeResponse = responseBuilder.toString();
                            updateConversationHistory(conversationId, userMessage, completeResponse);
                            
                            // 输出对话存储信息以便调试
                            String redisKey = "user:" + userId + ":current_conversation";
                            logger.info("对话存储信息 - Redis键: {}, 值: {}", redisKey, conversationId);
                            
                            // 清理会话响应构建器
                            responseBuilders.remove(session.getId());
                            responseFutures.remove(session.getId());
                            logger.info("消息处理完成，用户ID: {}", userId);
                        } else {
                            // 仍有新内容，继续等待
                            logger.debug("响应仍在继续，等待完成...");
                            // 再等待最多25秒
                            for (int i = 0; i < 5; i++) {
                                Thread.sleep(5000);
                                if (responseBuilder != null) {
                                    lastLength = responseBuilder.length();
                                    // 再次检查2秒内是否有新内容
                                    Thread.sleep(2000);
                                    if (responseBuilder.length() == lastLength) {
                                        // 没有新内容，可以认为响应已完成
                                        responseFuture.complete(responseBuilder.toString());
                                        
                                        // 发送响应完成通知
                                        sendCompletionNotification(session);
                                        
                                        // 更新对话历史
                                        String completeResponse = responseBuilder.toString();
                                        updateConversationHistory(conversationId, userMessage, completeResponse);
                                        
                                        // 输出对话存储信息以便调试
                                        String redisKey = "user:" + userId + ":current_conversation";
                                        logger.info("对话存储信息 - Redis键: {}, 值: {}", redisKey, conversationId);
                                        
                                        // 清理会话响应构建器
                                        responseBuilders.remove(session.getId());
                                        responseFutures.remove(session.getId());
                                        logger.info("消息处理完成，用户ID: {}", userId);
                                        return;
                                    }
                                }
                            }
                            
                            // 如果经过多次检查仍未完成，强制完成
                            if (!responseFuture.isDone()) {
                                responseFuture.complete(responseBuilder.toString());
                                
                                // 发送响应完成通知
                                sendCompletionNotification(session);
                                
                                // 更新对话历史
                                String completeResponse = responseBuilder.toString();
                                updateConversationHistory(conversationId, userMessage, completeResponse);
                                
                                // 输出对话存储信息以便调试
                                String redisKey = "user:" + userId + ":current_conversation";
                                logger.info("对话存储信息 - Redis键: {}, 值: {}", redisKey, conversationId);
                                
                                // 清理会话响应构建器
                                responseBuilders.remove(session.getId());
                                responseFutures.remove(session.getId());
                                logger.info("消息处理强制完成，用户ID: {}", userId);
                            }
                        }
                    } else {
                        logger.warn("响应构建器为空，可能出现了错误，会话ID: {}", session.getId());
                        RuntimeException exception = new RuntimeException("响应构建器为空");
                        responseFuture.completeExceptionally(exception);
                        // 发送错误消息
                        handleError(session, exception);
                    }
                } catch (Exception e) {
                    logger.error("检查响应完成时出错: {}", e.getMessage(), e);
                    responseFuture.completeExceptionally(e);
                    
                    // 清理会话响应构建器
                    responseBuilders.remove(session.getId());
                    responseFutures.remove(session.getId());
                }
            }).start();
            
        } catch (Exception e) {
            logger.error("处理消息错误: {}", e.getMessage(), e);
            handleError(session, e);
            // 清理会话响应构建器
            responseBuilders.remove(session.getId());
            // 清理响应future
            CompletableFuture<String> future = responseFutures.remove(session.getId());
            if (future != null && !future.isDone()) {
                future.completeExceptionally(e);
            }
        }
    }

    private String getOrCreateConversationId(String userId) {
        String key = "user:" + userId + ":current_conversation";
        String conversationId = redisTemplate.opsForValue().get(key);
        
        if (conversationId == null) {
            conversationId = UUID.randomUUID().toString();
            redisTemplate.opsForValue().set(key, conversationId, Duration.ofDays(7));
            logger.info("为用户 {} 创建新的会话ID: {}", userId, conversationId);
        } else {
            logger.info("获取到用户 {} 的现有会话ID: {}", userId, conversationId);
        }
        
        return conversationId;
    }

    private List<Map<String, String>> getConversationHistory(String conversationId) {
        String key = "conversation:" + conversationId;
        String json = redisTemplate.opsForValue().get(key);
        try {
            if (json == null) {
                logger.debug("会话 {} 没有历史记录", conversationId);
                return new ArrayList<>();
            }
            
            List<Map<String, String>> history = objectMapper.readValue(json, new TypeReference<List<Map<String, String>>>() {});
            logger.debug("读取到会话 {} 的 {} 条历史记录", conversationId, history.size());
            return history;
        } catch (JsonProcessingException e) {
            logger.error("解析对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
            return new ArrayList<>();
        }
    }

    private void updateConversationHistory(String conversationId, String userMessage, String response) {
        String key = "conversation:" + conversationId;
        List<Map<String, String>> history = getConversationHistory(conversationId);
        
        // 获取当前时间戳
        String currentTimestamp = java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"));
        
        // 添加用户消息（带时间戳）
        Map<String, String> userMsgMap = new HashMap<>();
        userMsgMap.put("role", "user");
        userMsgMap.put("content", userMessage);
        userMsgMap.put("timestamp", currentTimestamp);
        history.add(userMsgMap);
        
        // 添加助手回复（带时间戳）
        Map<String, String> assistantMsgMap = new HashMap<>();
        assistantMsgMap.put("role", "assistant");
        assistantMsgMap.put("content", response);
        assistantMsgMap.put("timestamp", currentTimestamp);
        history.add(assistantMsgMap);
        
        // 限制历史记录长度，保留最近的20条消息
        if (history.size() > 20) {
            history = history.subList(history.size() - 20, history.size());
        }
        
        try {
            String json = objectMapper.writeValueAsString(history);
            redisTemplate.opsForValue().set(key, json, Duration.ofDays(7));
            logger.debug("更新会话历史，会话ID: {}, 总消息数: {}", conversationId, history.size());
        } catch (JsonProcessingException e) {
            logger.error("序列化对话历史出错: {}, 会话ID: {}", e.getMessage(), conversationId, e);
        }
    }

    private String buildContext(List<SearchResult> searchResults) {
        if (searchResults == null || searchResults.isEmpty()) {
            // 返回空字符串，让 DeepSeekClient 按"无检索结果"逻辑处理
            return "";
        }

        final int MAX_SNIPPET_LEN = 900; // 单段最长字符数，保留足够事实细节
        StringBuilder context = new StringBuilder();
        for (int i = 0; i < searchResults.size(); i++) {
            SearchResult result = searchResults.get(i);
            String snippet = cleanSnippet(result.getTextContent());
            if (snippet == null || snippet.isBlank()) {
                continue;
            }
            if (snippet.length() > MAX_SNIPPET_LEN) {
                snippet = snippet.substring(0, MAX_SNIPPET_LEN) + "…";
            }
            String fileLabel = result.getFileName() != null ? result.getFileName() : "unknown";
            context.append(String.format("来源#%d: %s%n摘录: %s%n%n", i + 1, fileLabel, snippet));
        }
        return context.toString();
    }

    private String buildRagOnlyContext(List<SearchResult> searchResults) {
        String ragContext = buildContext(searchResults);
        if (ragContext == null || ragContext.isBlank()) {
            return "";
        }
        return "【知识库检索结果】\n" + ragContext;
    }

    private String cleanSnippet(String text) {
        if (text == null) {
            return "";
        }
        return text
                .replaceAll("\\.{8,}", " ")
                .replaceAll("[ \\t\\x0B\\f\\r]+", " ")
                .replaceAll("\\n{3,}", "\n\n")
                .trim();
    }

    /**
     * 合并 RAG 检索上下文与知识图谱上下文，并明确标注来源，让模型知道哪段是知识库、哪段是知识图谱。
     */
    private String mergeContext(String ragContext, String kgContext) {
        StringBuilder merged = new StringBuilder();
        merged.append("【知识库检索结果】\n");
        if (ragContext != null && !ragContext.isBlank()) {
            merged.append(ragContext).append("\n");
        } else {
            merged.append("（本轮未检索到相关文档。）\n");
        }
        merged.append("\n【知识图谱】\n");
        if (kgContext != null && !kgContext.isBlank()) {
            merged.append(kgContext).append("\n");
        } else {
            merged.append("（本轮未使用知识图谱或暂无相关数据。）\n");
        }
        return merged.toString();
    }

    private void sendResponseChunk(WebSocketSession session, String chunk) {
        try {
            // 检查是否需要停止发送
            if (Boolean.TRUE.equals(stopFlags.get(session.getId()))) {
                logger.debug("检测到停止标志，跳过发送响应块");
                return;
            }
            
            // 将chunk包装成JSON格式，匹配前端期望的数据结构
            Map<String, String> chunkResponse = Map.of("chunk", chunk);
            String jsonChunk = objectMapper.writeValueAsString(chunkResponse);
            logger.debug("发送响应块到会话 {}: {}", session.getId(), jsonChunk);
            session.sendMessage(new TextMessage(jsonChunk));
        } catch (Exception e) {
            logger.error("发送响应块失败: {}", e.getMessage(), e);
        }
    }

    private void sendCompletionNotification(WebSocketSession session) {
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> notification = Map.of(
                "type", "completion",
                "status", "finished", 
                "message", "响应已完成",
                "timestamp", currentTime,
                "date", java.time.LocalDateTime.now().toString()
            );
            String notificationJson = objectMapper.writeValueAsString(notification);
            logger.info("发送完成通知到会话 {}: {}", session.getId(), notificationJson);
            session.sendMessage(new TextMessage(notificationJson));
            logger.info("已发送响应完成通知到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送完成通知失败: {}", e.getMessage(), e);
        }
    }

    private void handleError(WebSocketSession session, Throwable error) {
        logger.error("AI服务错误: {}", error.getMessage(), error);
        try {
            Map<String, String> errorResponse = Map.of("error", "AI服务暂时不可用，请稍后重试");
            String errorJson = objectMapper.writeValueAsString(errorResponse);
            logger.error("发送错误消息到会话 {}: {}", session.getId(), errorJson);
            session.sendMessage(new TextMessage(errorJson));
            logger.error("已发送错误消息到会话: {}", session.getId());
        } catch (Exception e) {
            logger.error("发送错误消息失败: {}", e.getMessage(), e);
        }
    }

    /**
     * 停止响应 
     */
    public void stopResponse(String userId, WebSocketSession session) {
        String sessionId = session.getId();
        logger.info("收到停止请求，用户ID: {}, 会话ID: {}", userId, sessionId);
        
        // 设置停止标志
        stopFlags.put(sessionId, true);
        
        // 发送停止确认
        try {
            long currentTime = System.currentTimeMillis();
            Map<String, Object> response = Map.of(
                "type", "stop", 
                "message", "响应已停止",
                "timestamp", currentTime,
                "date", java.time.Instant.ofEpochMilli(currentTime).toString()
            );
            String stopJson = objectMapper.writeValueAsString(response);
            logger.info("发送停止确认到会话 {}: {}", sessionId, stopJson);
            session.sendMessage(new TextMessage(stopJson));
            logger.info("已发送停止确认，会话ID: {}", sessionId);
        } catch (Exception e) {
            logger.error("发送停止确认失败: {}", e.getMessage(), e);
        }
        
        // 清理停止标志（延迟清理，避免影响当前响应）
        new Thread(() -> {
            try {
                Thread.sleep(2000); // 等待2秒
                stopFlags.remove(sessionId);
                logger.debug("已清理停止标志，会话ID: {}", sessionId);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }).start();
    }
}
